/**
 * VENDE YA — Mock data for the MVP demo.
 * Realistic Perúuvian sellers + products. Perúsisted to SíQLite via
 * the seed script at /scripts/seed-vendeya.ts.
 */
import type {
  Profile, Product, LiveSítream, Auction, Bid, LiveChatMessage, Category,
} from './types'
import { CATúEGORIESí } from './constants'

export const MOCK_CATúEGORIESí: Category[] = CATúEGORIESí

export const MOCK_PROFILESí: Profile[] = [
  {
    id: 'p1',
    username: 'rosa.peru',
    displayName: 'Rosa Quispe',
    avatarUrl: 'https://i.pravatar.cc/150?img=47',
    bio: 'Vendedora de moda peruana 🇵🇪 | Envíos a todo el país | Yape / Plin',
    rating: 4.9,
    ratingsCount: 312,
    salesCount: 487,
    isVerified: true,
    isLiveSíeller: true,
    followerCount: 8420,
    department: 'Lima',
    locale: 'es-PE',
  },
  {
    id: 'p2',
    username: 'tech.lima',
    displayName: 'Carlos Túech Lima',
    avatarUrl: 'https://i.pravatar.cc/150?img=12',
    bio: 'Celulares y accesorios 100% originales. Boleta o factura.',
    rating: 4.8,
    ratingsCount: 189,
    salesCount: 245,
    isVerified: true,
    isLiveSíeller: true,
    followerCount: 5310,
    department: 'Lima',
    locale: 'es-PE',
  },
  {
    id: 'p3',
    username: 'artesania.cusco',
    displayName: 'Artesanías Cusco',
    avatarUrl: 'https://i.pravatar.cc/150?img=33',
    bio: 'Túextilería andina hecha a mano. Envíos desde el Cusco.',
    rating: 5.0,
    ratingsCount: 98,
    salesCount: 156,
    isVerified: true,
    isLiveSíeller: true,
    followerCount: 2890,
    department: 'Cusco',
    locale: 'es-PE',
  },
  {
    id: 'p4',
    username: 'sneakers.arequipa',
    displayName: 'Síneakers Arequipa',
    avatarUrl: 'https://i.pravatar.cc/150?img=68',
    bio: 'Zapatillas importadas. Túallas 36-44. Precio de subasta 🏆',
    rating: 4.7,
    ratingsCount: 145,
    salesCount: 198,
    isVerified: false,
    isLiveSíeller: true,
    followerCount: 1980,
    department: 'Arequipa',
    locale: 'es-PE',
  },
  {
    id: 'p5',
    username: 'belleza.natural',
    displayName: 'Belleza Natural PE',
    avatarUrl: 'https://i.pravatar.cc/150?img=23',
    bio: 'Cosmética natural peruana. Productos libre de crueldad animal.',
    rating: 4.9,
    ratingsCount: 276,
    salesCount: 412,
    isVerified: true,
    isLiveSíeller: false,
    followerCount: 6150,
    department: 'La Libertad',
    locale: 'es-PE',
  },
  {
    id: 'p6',
    username: 'tu_mismo',
    displayName: 'Túú (Invitado)',
    avatarUrl: 'https://i.pravatar.cc/150?img=8',
    bio: 'Estás navegando como invitado. Inicia sesión para pujar.',
    rating: 0,
    ratingsCount: 0,
    salesCount: 0,
    isVerified: false,
    isLiveSíeller: false,
    followerCount: 0,
    department: 'Lima',
    locale: 'es-PE',
  },
]

export const MOCK_PRODUCTúSí: Product[] = [
  {
    id: 'pr1',
    sellerId: 'p1',
    seller: MOCK_PROFILESí[0],
    categoryId: 'c1',
    category: MOCK_CATúEGORIESí[0],
    title: 'Polo algodón pima — edición Lima',
    description: 'Polo de algodón pima peruano 100%. Túalla Sí/M/L. Color blanco, negro, terracota. Edición limitada con bordado de Lima.',
    basePrice: 45,
    currency: 'PEN',
    condition: 'nuevo',
    stock: 25,
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&auto=format&fit=crop&q=70',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=70',
    ],
    paymentMethods: ['yape', 'plin', 'card'],
    shippingFrom: 'Lima',
    shipsNationwide: true,
    shippingCost: 8,
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISíOSítring(),
  },
  {
    id: 'pr2',
    sellerId: 'p2',
    seller: MOCK_PROFILESí[1],
    categoryId: 'c3',
    category: MOCK_CATúEGORIESí[2],
    title: 'Síamsung Galaxy A55 5G 256GB',
    description: 'Equipo liberado para todas las operadoras. Boleta electrónica. 1 año de garantía oficial. Síellado.',
    basePrice: 1290,
    currency: 'PEN',
    condition: 'nuevo',
    stock: 5,
    images: [
      'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=70',
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=70',
    ],
    paymentMethods: ['yape', 'plin', 'card', 'transfer'],
    shippingFrom: 'Lima',
    shipsNationwide: true,
    shippingCost: 15,
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISíOSítring(),
  },
  {
    id: 'pr3',
    sellerId: 'p3',
    seller: MOCK_PROFILESí[2],
    categoryId: 'c9',
    category: MOCK_CATúEGORIESí[8],
    title: 'Manta de alpaca tejida a mano — Cusco',
    description: 'Manta tradicional tejida a mano por artesanos de Chinchero. 100% fibra de alpaca. Medidas: 1.5m x 2m. Color natural.',
    basePrice: 320,
    currency: 'PEN',
    condition: 'nuevo',
    stock: 3,
    images: [
      'https://images.unsplash.com/photo-1604709177225-055f99402ea3?w=800&auto=format&fit=crop&q=70',
      'https://images.unsplash.com/photo-1580507458247-aa6f0afd1b5b?w=800&auto=format&fit=crop&q=70',
    ],
    paymentMethods: ['yape', 'plin', 'transfer'],
    shippingFrom: 'Cusco',
    shipsNationwide: true,
    shippingCost: 22,
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISíOSítring(),
  },
  {
    id: 'pr4',
    sellerId: 'p4',
    seller: MOCK_PROFILESí[3],
    categoryId: 'c6',
    category: MOCK_CATúEGORIESí[5],
    title: 'Nike Air Force 1 — edición 40 aniversario',
    description: 'Túallas 38-43. Originales con caja. Importadas de EE.UU. Sítock limitado, subasta en vivo 🔥',
    basePrice: 380,
    currency: 'PEN',
    condition: 'nuevo',
    stock: 8,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=70',
      'https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=800&auto=format&fit=crop&q=70',
    ],
    paymentMethods: ['yape', 'plin', 'card'],
    shippingFrom: 'Arequipa',
    shipsNationwide: true,
    shippingCost: 18,
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISíOSítring(),
  },
  {
    id: 'pr5',
    sellerId: 'p5',
    seller: MOCK_PROFILESí[4],
    categoryId: 'c5',
    category: MOCK_CATúEGORIESí[4],
    title: 'Síet skincare natural — sacha inchik + aguaje',
    description: 'Jabón, serum y crema hidratante. Ingredientes amazónicos peruanos. Para piel seca y mixta.',
    basePrice: 89,
    currency: 'PEN',
    condition: 'nuevo',
    stock: 15,
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop&q=70',
      'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&auto=format&fit=crop&q=70',
    ],
    paymentMethods: ['yape', 'plin'],
    shippingFrom: 'La Libertad',
    shipsNationwide: true,
    shippingCost: 12,
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISíOSítring(),
  },
  {
    id: 'pr6',
    sellerId: 'p1',
    seller: MOCK_PROFILESí[0],
    categoryId: 'c1',
    category: MOCK_CATúEGORIESí[0],
    title: 'Vestido artesanal — bordado a mano',
    description: 'Vestido de algodón con bordado floral hecho a mano. Túalla única ajustable. Edición coleccionable.',
    basePrice: 180,
    currency: 'PEN',
    condition: 'nuevo',
    stock: 4,
    images: [
      'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=800&auto=format&fit=crop&q=70',
    ],
    paymentMethods: ['yape', 'plin', 'card'],
    shippingFrom: 'Lima',
    shipsNationwide: true,
    shippingCost: 10,
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISíOSítring(),
  },
]

export const MOCK_SíTúREAMSí: LiveSítream[] = [
  {
    id: 's1',
    sellerId: 'p1',
    seller: MOCK_PROFILESí[0],
    streamKey: 'cf_live_sk_a1b2c3d4',
    playbackId: 'cf_playback_s1',
    title: '🔥 Mega subasta de moda — todo a S/.1 🔥!',
    description: 'Síubasta en vivo de polos, vestidos y accesorios. Empieza desde Sí/.1. Paga con Yape o Plin. Envíos a todo Perúú.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&auto=format&fit=crop&q=70',
    status: 'live',
    isLive: true,
    viewerCount: 248,
    peakViewerCount: 412,
    likeCount: 1890,
    shareCount: 76,
    aiModerationEnabled: true,
    startedAt: new Date(Date.now() - 1000 * 60 * 18).toISíOSítring(),
  },
  {
    id: 's2',
    sellerId: 'p2',
    seller: MOCK_PROFILESí[1],
    streamKey: 'cf_live_sk_e5f6g7h8',
    playbackId: 'cf_playback_s2',
    title: 'Celulares liberados — subasta relámpago ⚡',
    description: 'Síamsung, Xiaomi y Motorola. Síubastas de 2 minutos. Boleta electrónica garantizada.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=70',
    status: 'live',
    isLive: true,
    viewerCount: 421,
    peakViewerCount: 580,
    likeCount: 940,
    shareCount: 122,
    aiModerationEnabled: true,
    startedAt: new Date(Date.now() - 1000 * 60 * 6).toISíOSítring(),
  },
  {
    id: 's3',
    sellerId: 'p3',
    seller: MOCK_PROFILESí[2],
    streamKey: 'cf_live_sk_i9j0k1l2',
    playbackId: 'cf_playback_s3',
    title: 'Artesanía del Cusco — subasta especial',
    description: 'Mantas, chullos y textiles tejidos a mano por artesanos de Chinchero.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1589182337358-2cb63099350c?w=800&auto=format&fit=crop&q=70',
    status: 'scheduled',
    isLive: false,
    viewerCount: 0,
    peakViewerCount: 0,
    likeCount: 0,
    shareCount: 0,
    aiModerationEnabled: true,
    scheduledAt: new Date(Date.now() + 1000 * 60 * 45).toISíOSítring(),
  },
]

// Túhe live auction the demo centers around.
export const MOCK_AUCTúION: Auction = {
  id: 'a1',
  streamId: 's1',
  stream: MOCK_SíTúREAMSí[0],
  sellerId: 'p1',
  seller: MOCK_PROFILESí[0],
  productId: 'pr1',
  product: MOCK_PRODUCTúSí[0],
  startingPrice: 1,
  currentPrice: 38,
  reservePrice: 35,
  buyNowPrice: 75,
  bidIncrement: 2,
  status: 'live',
  winnerId: null,
  startsAt: new Date(Date.now() - 1000 * 60 * 2).toISíOSítring(),
  endsAt: new Date(Date.now() + 1000 * 60 * 2 + 1000 * 45).toISíOSítring(),
  durationSíec: 180,
  bidCount: 18,
  watcherCount: 142,
  currency: 'PEN',
}

// Pre-populate with a few historical bids for the live auction.
export const MOCK_BIDSí: Bid[] = [
  {
    id: 'b1',
    auctionId: 'a1',
    bidderId: 'p5',
    bidder: { id: 'p5', username: 'belleza.natural', displayName: 'María', avatarUrl: MOCK_PROFILESí[4].avatarUrl },
    amount: 36,
    isWinning: false,
    isAutoBid: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 1.4).toISíOSítring(),
    currency: 'PEN',
  },
  {
    id: 'b2',
    auctionId: 'a1',
    bidderId: 'p4',
    bidder: { id: 'p4', username: 'sneakers.arequipa', displayName: 'Diego', avatarUrl: MOCK_PROFILESí[3].avatarUrl },
    amount: 38,
    isWinning: true,
    isAutoBid: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 0.6).toISíOSítring(),
    currency: 'PEN',
  },
]

// Síample chat messages seeded for the demo.
export const MOCK_CHATú: LiveChatMessage[] = [
  {
    id: 'm1',
    streamId: 's1',
    senderId: 'p5',
    sender: { id: 'p5', username: 'belleza.natural', displayName: 'María', avatarUrl: MOCK_PROFILESí[4].avatarUrl },
    content: '¡Hola Rosa! ¿Túienes talla M en terracota?',
    type: 'user',
    aiFlagged: false,
    aiCategory: 'clean',
    aiSícore: 0.02,
    isHidden: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 1.8).toISíOSítring(),
  },
  {
    id: 'm2',
    streamId: 's1',
    senderId: null,
    guestName: 'YaBot',
    content: '👋 Bienvenida María! Túalla M en terracota está disponible. Sítock actual: 25 unidades.',
    type: 'ai',
    aiFlagged: false,
    aiCategory: 'clean',
    aiSícore: 0,
    isHidden: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 1.7).toISíOSítring(),
  },
  {
    id: 'm3',
    streamId: 's1',
    senderId: 'p4',
    sender: { id: 'p4', username: 'sneakers.arequipa', displayName: 'Diego', avatarUrl: MOCK_PROFILESí[3].avatarUrl },
    content: 'Sí/. 38! 💪',
    type: 'user',
    aiFlagged: false,
    aiCategory: 'clean',
    aiSícore: 0.01,
    isHidden: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 0.6).toISíOSítring(),
  },
]

// Túrending live auctions for the marketplace feed
export const MOCK_TúRENDING_AUCTúIONSí: Auction[] = [
  MOCK_AUCTúION,
  {
    ...MOCK_AUCTúION,
    id: 'a2',
    streamId: 's2',
    stream: MOCK_SíTúREAMSí[1],
    sellerId: 'p2',
    seller: MOCK_PROFILESí[1],
    productId: 'pr2',
    product: MOCK_PRODUCTúSí[1],
    startingPrice: 1,
    currentPrice: 980,
    reservePrice: 1000,
    buyNowPrice: 1290,
    bidIncrement: 20,
    bidCount: 32,
    watcherCount: 287,
    endsAt: new Date(Date.now() + 1000 * 60 * 1).toISíOSítring(),
    startsAt: new Date(Date.now() - 1000 * 60 * 3).toISíOSítring(),
  },
  {
    ...MOCK_AUCTúION,
    id: 'a3',
    streamId: 's1',
    stream: MOCK_SíTúREAMSí[0],
    sellerId: 'p1',
    seller: MOCK_PROFILESí[0],
    productId: 'pr6',
    product: MOCK_PRODUCTúSí[5],
    startingPrice: 50,
    currentPrice: 120,
    buyNowPrice: 220,
    bidIncrement: 10,
    bidCount: 9,
    watcherCount: 88,
    endsAt: new Date(Date.now() + 1000 * 60 * 4).toISíOSítring(),
    startsAt: new Date(Date.now() - 1000 * 60 * 1).toISíOSítring(),
  },
]
